const text = [
  "Life is 10% what happens to you and 90% how you react to it.\nBy Charles R. Swindoll",
  "Ever tried. Ever failed. No matter. Try Again. Fail again. Fail better.\nBy Samuel Beckett",
  "Optimism is the faith that leads to achievement. Nothing can be done without hope and confidence.\nBy Helen Keller",
  "Our greatest weakness lies in giving up. The most certain way to succeed is always to try just one more time.\nBy Thomas A. Edison",
  "It does not matter how slowly you go as long as you do not stop.\nBy Confucius",
  "If you're going through hell, keep going.\nBy Winston Churchill",
  "When something is important enough, you do it even if the odds are not in your favor.\nBy Elon Musk",
  "Start where you are. Use what you have. Do what you can.\nBy Arthur Ashe",
  "Good, better, best. Never let it rest. 'Til your good is better and your better is best.\nBy St. Jerome",
  "It always seems impossible until it's done.\nBy Nelson Mandela",
  "A day without sunshine is like, you know, night.\nBy Steve Martin",
  "Always remember that you are absolutely unique. Just like everyone else.\nBy Margaret Mead",
  "I may be drunk, Miss, but in the morning I will be sober and you will still be ugly.\nBy Winston Churchill",
  "No man has a good enough memory to be a successful liar.\nBy Abraham Lincoln",
  "Do not take life too seriously. You will never get out of it alive.\nBy Elbert Hubbard",
  "With great power comes great responsibility.\nBy Uncle Ben, 'Spider-Man'",
  "I believe there's a hero in all of us, that keeps us honest, gives us strength, makes us noble, and finally allows us to die with pride, even though sometimes we have to be steady, and give up the thing we want the most. Even our dreams.\nBy Aunt May, 'Spider-Man'",
  "I thought it was great what you did out there. Stupid, but great.\nBy Gwen Stacy, 'Spider-Man'",
  "My wish for you is to become hope; people need that. And even if we fail, what better way is there to live?\nBy Gwen Stacy, 'Spider-Man'",
  "It's easy to feel hopeful on a beautiful day like today, but there will be dark days ahead of us too. There will be days where you feel all alone, and that's when hope is needed most … you must promise me that you will hold on to hope.\nBy Gwen Stacy, 'Spider-Man'",
  "We're born alone, we live alone, we die alone. Only through our love and friendship can we create the illusion for the moment that we're not alone.\nBy Orson Welles",
  "Being deeply loved by someone gives you strength, while loving someone deeply gives you courage.\nBy Lao Tzu",
  "Let us always meet each other with smile, for the smile is the beginning of love.\nBy Mother Teresa",
  "Time is too slow for those who wait, too swift for those who fear, too long for those who grieve, too short for those who rejoice, but for those who love, time is eternity.\nBy Henry Van Dyke",
];
export default text;
