const text = [
  "Life is 10% what happens to you and 90% how you react to it.\n-Charles R. Swindoll",
  "Ever tried. Ever failed. No matter. Try Again. Fail again. Fail better.\n-Samuel Beckett",
  "Optimism is the faith that leads to achievement. Nothing can be done without hope and confidence.\n-Helen Keller",
  "Our greatest weakness lies in giving up. The most certain way to succeed is always to try just one more time.\n-Thomas A. Edison",
  "It does not matter how slowly you go as long as you do not stop.\n-Confucius",
  "If you're going through hell, keep going.\n-Winston Churchill",
  "When something is important enough, you do it even if the odds are not in your favor.\n-Elon Musk",
  "Start where you are. Use what you have. Do what you can.\n-Arthur Ashe",
  "Good, better, best. Never let it rest. 'Til your good is better and your better is best.\n-St. Jerome",
  "It always seems impossible until it's done.\n-Nelson Mandela",
  "A day without sunshine is like, you know, night.\n-Steve Martin",
  "Always remember that you are absolutely unique. Just like everyone else.\n-Margaret Mead",
  "I may be drunk, Miss, but in the morning I will be sober and you will still be ugly.\n-Winston Churchill",
  "No man has a good enough memory to be a successful liar.\n-Abraham Lincoln",
  "Do not take life too seriously. You will never get out of it alive.\n-Elbert Hubbard",
  "With great power comes great responsibility.\n-Uncle Ben, 'Spider-Man'",
  "I believe there's a hero in all of us, that keeps us honest, gives us strength, makes us noble, and finally allows us to die with pride, even though sometimes we have to be steady, and give up the thing we want the most. Even our dreams.\n-Aunt May, 'Spider-Man'",
  "I thought it was great what you did out there. Stupid, but great.\n-Gwen Stacy, 'Spider-Man'",
  "My wish for you is to become hope; people need that. And even if we fail, what better way is there to live?\n-Gwen Stacy, 'Spider-Man'",
  "It's easy to feel hopeful on a beautiful day like today, but there will be dark days ahead of us too. There will be days where you feel all alone, and that's when hope is needed most … you must promise me that you will hold on to hope.\n-Gwen Stacy, 'Spider-Man'",
  "We're born alone, we live alone, we die alone. Only through our love and friendship can we create the illusion for the moment that we're not alone.\n-Orson Welles",
  "Being deeply loved -someone gives you strength, while loving someone deeply gives you courage.\n-Lao Tzu",
  "Let us always meet each other with smile, for the smile is the beginning of love.\n-Mother Teresa",
  "Time is too slow for those who wait, too swift for those who fear, too long for those who grieve, too short for those who rejoice, but for those who love, time is eternity.\n-Henry Van Dyke",
  "The greatest glory in living lies not in never falling, but in rising every time we fall. \n-Nelson Mandela",
  "The way to get started is to quit talking and begin doing. \n-Walt Disney",
  "Your time is limited, so don't waste it living someone else's life. Don't be trapped -dogma - which is living with the results of other people's thinking. \n-Steve Jobs",
  "If life were predictable it would cease to be life, and be without flavor. \n-Eleanor Roosevelt",
  "If you look at what you have in life, you'll always have more. If you look at what you don't have in life, you'll never have enough. \n-Oprah Winfey",
  "If you set your goals ridiculously high and it's a failure, you will fail above everyone else's success. \n-James Cameron",
  "Spread love everywhere you go. Let no one ever come to you without leaving happier. \n-Mother Teresa",
  "Tell me and I forget. Teach me and I remember. Involve me and I learn. \n-Benjamin Franklin",
  "Do not go where the path may lead, go instead where there is no path and leave a trail. \n-Ralph Waldo",
];
export default text;
